#! /bin/bash

tmpdir="/var/spool/cups/tmp"
input_pdf="input.pdf"

# Parse settings from input PDF file
if [ -f $input_pdf ]
then

	lineIndex=0
	readCntr=0

	while read -r line; do 

		lineIndex=$((lineIndex+1))

		echo "Read line $lineIndex"

		if [[ "$line" == *"%%PDFTOPDFNumCopies : "* ]]; then

			readCntr=$((readCntr+1))
			echo "Finded substring in line $lineIndex"
			lineLen=${#line}
			echo "Line Length $lineLen"
			subLen=$((lineLen-22))
			echo "Subline Length $subLen"
			copiesNum=${line:22:$subLen}
			echo "Number of Copies: $copiesNum"
		fi


		if [[ "$line" == *"%%PDFTOPDFCollate : "* ]]; then

			readCntr=$((readCntr+1))
			echo "Finded substring in line $lineIndex"
			lineLen=${#line}
			echo "Line Length $lineLen"
			subLen=$((lineLen-20))
			echo "Subline Length $subLen"
			collateCopies=${line:20:$subLen}
			echo "Collate Copies: $collateCopies"
		fi

		if [[ "$readCntr" == "2" ]]; then 
			break
		fi

	done < $input_pdf
else
	echo "Input PDF file not exist"
	exit 1
fi

exit 0
